name: CI/CD Pipeline for AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR File
        run: mvn clean package

      - name: Log in to Amazon ECR
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}" | docker login -u AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build and Push Docker Image
        run: |
          docker build -t springboot-app .
          docker tag springboot-app:latest ${{ secrets.ECR_REPO }}/springboot-app:latest
          docker push ${{ secrets.ECR_REPO }}/springboot-app:latest

      - name: Deploy to AWS ECS
        run: |
          aws ecs update-service --cluster springboot-cluster --service springboot-service --force-new-deployment
